<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>HOMER | WebApp admin theme</title>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!--<link rel="shortcut icon" type="<?php echo $baseUrl; ?>assets/image//ico" href="favicon.ico" />-->

    <!-- Vendor styles -->
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/metisMenu/dist/metisMenu.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/animate.css/animate.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/datatables.net-bs/css/dataTables.bootstrap.min.css" />

    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/ladda/dist/ladda-themeless.min.css" />

    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/toastr/build/toastr.min.css" />

    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/sweetalert/lib/sweet-alert.css" />

    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css" />

    <!-- App styles -->
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/fonts/pe-icon-7-stroke/css/helper.css" />
    <link rel="stylesheet" href="<?php echo $baseUrl; ?>assets/styles/style.css">

    <style media="screen">
    .dt-buttons{
      display: none;
    }
    </style>

    <style media="screen">
    .modal-body.custom {
      padding: 0 30px;
    }
    .pd-tb-10 {
      padding: 10px 0;
    }
    .tb-active {
      background-color: #34495e !important;
      border-color: #34495e !important;
      color: #fff !important;
    }
    </style>

</head>
<body class="fixed-navbar sidebar-scroll">

<!-- Simple splash screen-->
<div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
<!--[if lt IE 7]>
<p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Header -->
<div id="header">
    <div class="color-line">
    </div>
    <div id="logo" class="light-version">
        <span>
            Homer Theme
        </span>
    </div>
    <nav role="navigation">
        <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
        <div class="small-logo">
            <span class="text-primary">HOMER APP</span>
        </div>
        <form role="search" class="navbar-form-custom" method="post" action="#">
            <div class="form-group">
                <input type="text" placeholder="Search something special" class="form-control" name="search">
            </div>
        </form>
        <div class="mobile-menu">
            <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
                <i class="fa fa-chevron-down"></i>
            </button>
            <div class="collapse mobile-navbar" id="mobile-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="" href="login.html">Login</a>
                    </li>
                    <li>
                        <a class="" href="login.html">Logout</a>
                    </li>
                    <li>
                        <a class="" href="profile.html">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav no-borders">
                <li class="dropdown">
                    <a href="<?php echo $baseUrl; ?>logout">
                        <i class="pe-7s-upload pe-rotate-90"></i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<!-- Navigation -->
<aside id="menu">
    <div id="navigation">
        <div class="profile-picture">
            <a href="index.html">
                <img src="<?php echo $baseUrl; ?>assets/images/profile.jpg" class="img-circle m-b" alt="logo">
            </a>

            <div class="stats-label text-color">
                <span class="font-extra-bold font-uppercase">Robert Razer</span>

                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <small class="text-muted">Founder of App <b class="caret"></b></small>
                    </a>
                    <ul class="dropdown-menu animated flipInX m-t-xs">
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="analytics.html">Analytics</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>


                <div id="sparkline1" class="small-chart m-t-sm"></div>
                <div>
                    <h4 class="font-extra-bold m-b-xs">
                        $260 104,200
                    </h4>
                    <small class="text-muted">Your income from the last year in sales product X.</small>
                </div>
            </div>
        </div>

        <?php echo $sideMenu; ?>
    </div>
</aside>

<!-- Main Wrapper -->
<div id="wrapper">

  <div class="small-header">
      <div class="hpanel">
          <div class="panel-body">
              <div id="hbreadcrumb" class="pull-right">
                  <ol class="hbreadcrumb breadcrumb">
                      <li><a href="index.html">Dashboard</a></li>
                      <li>
                          <span>Forms</span>
                      </li>
                      <li class="active">
                          <span>Validation </span>
                      </li>
                  </ol>
              </div>
              <h2 class="font-light m-b-xs">
                  Master Employee
              </h2>
              <small>Build a form with validation functionality</small>
          </div>
      </div>
  </div>


  <div class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    Datatables
                </div>
                <div class="panel-body">
                    <table id="example1" class="table table-striped table-bordered table-hover" width="100%">
                        <thead>
                        <tr>
                            <th width="5%">No.</th>
                            <th>ID</th>
                            <th>Code</th>
                            <th>Name</th>
                            <th>Unit</th>
                            <th>Jabatan</th>
                            <th width="15%">Action</th>
                        </tr>
                        </thead>
                    </table>
                    <div class="row">
                      <div class="col-sm-12">
                        <button id="btnAdd" class="btn btn-primary" data-toggle="modal" data-target="#myModal5"><i class="fa fa-plus"></i> Add</button>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>

    <!-- Footer-->
    <footer class="footer">
        <span class="pull-right">
            Example text
        </span>
        Company 2015-2020
    </footer>

</div>

<div class="modal fade" id="myModal5" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 class="modal-title">Tambah Employee</h4>
            </div>
            <form action="<?php echo $baseUrl; ?>api/employee/add" role="form" id="form_2" class="pd-tb-10">
                <input type="hidden" id="<?php echo $primaryKey; ?>" name="<?php echo $primaryKey; ?>">
                <div class="modal-body">
                  <div class="text-center m-b-md" id="wizardControl">
                      <a class="btn btn-default ln-tb-step tb-active" href="#step1" data-toggle="tab" id="ln-tb-step1">Step 1 - Personal data</a>
                      <a class="btn btn-default ln-tb-step" href="#step2" data-toggle="tab" id="ln-tb-step2">Step 2 - Address & Contact</a>
                      <a class="btn btn-default ln-tb-step" href="#step3" data-toggle="tab" id="ln-tb-step3">Step 3 - Bank & Insurance</a>
                      <a class="btn btn-default ln-tb-step" href="#step4" data-toggle="tab" id="ln-tb-step4">Step 4 - Employee Info</a>
                  </div>
                  <div class="tab-content">
                    <div id="step1" class="p-m tab-pane active">
                        <div class="row text-center">
                          <div class="col-lg-12">
                              <i class="pe-7s-user fa-5x text-muted"></i>
                              <p class="small m-t-md">
                                  This is personal data information
                              </p>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                      <label for="emp_name">Nama Employee</label>
                                      <input type="text" id="emp_name" name="emp_name" placeholder="Isi nama employee" class="form-control" required>
                                    </div>
                                    <div class="form-group col-lg-6">
                                      <label for="emp_initial">Initial</label>
                                      <input type="text" id="emp_initial" name="emp_initial" placeholder="Isi initial" class="form-control" required>
                                    </div>
                                    <div class="form-group col-lg-6">
                                      <label for="emp_code">Code</label>
                                      <input type="text" id="emp_code" name="emp_code" placeholder="Isi employee code" class="form-control" required>
                                    </div>
                                    <div class="form-group col-lg-6">
                                      <label for="emp_NIK">NIK</label>
                                      <input type="text" id="emp_NIK" name="emp_NIK" placeholder="Isi employee NIK" class="form-control" required>
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <label for="emp_gender">Gender</label>
                                      <select id="emp_gender" name="emp_gender" placeholder="Isi Jenis Kelamin" class="form-control">
                                        <<option value="">-- Pilih Jenis Kelamin --</option>
                                        <?php foreach($optGender as $value): ?>
                                        <option value="<?php echo $value['key']; ?>"><?php echo $value['value']; ?></option>
                                        <?php endforeach; ?>
                                      </select>
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <div class="row">
                                        <div class="form-group col-lg-6">
                                          <label for="emp_birthplace">Birth Place</label>
                                          <input type="text" id="emp_birthplace" name="emp_birthplace" placeholder="Isi birth place" class="form-control">
                                        </div>
                                        <div class="form-group col-lg-6">
                                          <label for="emp_birthdate">Birth Date</label>
                                          <input type="text" id="emp_birthdate" name="emp_birthdate" placeholder="Isi birth date" class="form-control datepicker">
                                        </div>
                                      </div>
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <label for="emp_religion">Religion</label>
                                      <select id="emp_religion" name="emp_religion" placeholder="Isi nama religion" class="form-control">
                                        <<option value="">-- Pilih Religion --</option>
                                        <?php foreach($optReligion as $value): ?>
                                        <option value="<?php echo $value['key']; ?>"><?php echo $value['value']; ?></option>
                                        <?php endforeach; ?>
                                      </select>
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <label for="emp_marital_status">Marital Status</label>
                                      <select id="emp_marital_status" name="emp_marital_status" placeholder="Isi marital status" class="form-control">
                                        <<option value="">-- Pilih Marital Status --</option>
                                        <?php foreach($optStatusMarried as $value): ?>
                                        <option value="<?php echo $value['key']; ?>"><?php echo $value['value']; ?></option>
                                        <?php endforeach; ?>
                                      </select>
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <div class="row">
                                        <div class="form-group col-lg-6">
                                          <label for="emp_tanggal_perkawinan">Tanggal Perkawinan</label>
                                          <input type="text" id="emp_tanggal_perkawinan" name="emp_tanggal_perkawinan" placeholder="Isi tanggal perkawinan" class="form-control datepicker">
                                        </div>
                                        <div class="form-group col-lg-6">
                                          <label for="emp_jumlah_anak">Jumlah Anak</label>
                                          <input type="text" id="emp_jumlah_anak" name="emp_jumlah_anak" placeholder="Isi jumlah anak" class="form-control">
                                        </div>
                                      </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="step2" class="p-m tab-pane">
                        <div class="row text-center">
                          <div class="col-lg-12">
                              <i class="pe-7s-id fa-5x text-muted"></i>
                              <p class="small m-t-md">
                                  This is address & contact data information
                              </p>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-4">
                                      <label for="emp_address1">Address 1</label>
                                      <input type="text" id="emp_address1" name="emp_address1" placeholder="Isi address 1" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-4">
                                      <label for="emp_address2">Address 2</label>
                                      <input type="text" id="emp_address2" name="emp_address2" placeholder="Isi address 2" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-4">
                                      <label for="emp_address3">Address 3</label>
                                      <input type="text" id="emp_address3" name="emp_address3" placeholder="Isi address 3" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="emp_post_code">Post Code</label>
                                        <input type="text" id="emp_post_code" name="emp_post_code" placeholder="Isi post code" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-3">
                                      <label for="emp_ext_phone">Ext Phone</label>
                                      <input type="text" id="emp_ext_phone" name="emp_ext_phone" placeholder="Isi ext phone" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-3">
                                      <label for="emp_office_phone">Office Phone</label>
                                      <input type="text" id="emp_office_phone" name="emp_office_phone" placeholder="Isi office phone" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-3">
                                      <label for="emp_home_phone">Home Phone</label>
                                      <input type="text" id="emp_home_phone" name="emp_home_phone" placeholder="Isi home phone" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-3">
                                      <label for="emp_mobile_phone">Mobile Phone</label>
                                      <input type="text" id="emp_mobile_phone" name="emp_mobile_phone" placeholder="Isi mobile phone" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-12">
                                      <label for="emp_pin_bb">Pin BB</label>
                                      <input type="text" id="emp_pin_bb" name="emp_pin_bb" placeholder="Isi pin bb" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                      <label for="emp_email">Email</label>
                                      <input type="text" id="emp_email" name="emp_email" placeholder="Isi email" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                      <label for="emp_website">Web Site</label>
                                      <input type="text" id="emp_website" name="emp_website" placeholder="Isi website" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="step3" class="p-m tab-pane">
                        <div class="row text-center">
                          <div class="col-lg-12">
                              <i class="pe-7s-credit fa-5x text-muted"></i>
                              <p class="small m-t-md">
                                  This is bank & insurance data information
                              </p>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-4">
                                        <label for="emp_acc_bank">Account Bank</label>
                                        <input type="text" id="emp_acc_bank" name="emp_acc_bank" placeholder="Isi account bank" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <label for="emp_acc_no">Account No</label>
                                        <input type="text" id="emp_acc_no" name="emp_acc_no" placeholder="Isi account no" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <label for="emp_acc_name">Account Name</label>
                                        <input type="text" id="emp_acc_name" name="emp_acc_name" placeholder="Isi account name" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_bpjs_ketenagakerjaan">BPJS Ketenagakerjaan</label>
                                        <input type="text" id="emp_bpjs_ketenagakerjaan" name="emp_bpjs_ketenagakerjaan" placeholder="Isi BPJS Ketenagakerjaan" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_bpjs_kesehatan">BPJS Kesehatan</label>
                                        <input type="text" id="emp_bpjs_kesehatan" name="emp_bpjs_kesehatan" placeholder="Isi BPJS Kesehatan" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_npwp">NPWP</label>
                                        <input type="text" id="emp_npwp" name="emp_npwp" placeholder="Isi NPWP" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="step4" class="p-m tab-pane">
                        <div class="row text-center">
                          <div class="col-lg-12">
                              <i class="pe-7s-medal fa-5x text-muted"></i>
                              <p class="small m-t-md">
                                  This is employee data information
                              </p>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label for="emp_active">Employee Active</label> <input type="text" id="emp_active" name="emp_active" placeholder="Isi employee active" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_start_date">Start Date</label> <input type="text" id="emp_start_date" name="emp_start_date" placeholder="Isi start date" class="form-control datepicker">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_out_date">Out Date</label> <input type="text" id="emp_out_date" name="emp_out_date" placeholder="Isi out date" class="form-control datepicker">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="emp_reason_out">Reason Out</label> <input type="text" id="emp_reason_out" name="emp_reason_out" placeholder="Isi reason out" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="emp_photo">Photo</label> <input type="text" id="emp_photo" name="emp_photo" placeholder="Isi photo" class="form-control">
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="emp_base_salary">Base Salary</label> <input type="text" id="emp_base_salary" name="emp_base_salary" placeholder="Isi base salary" class="form-control autonumeric">
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="emp_uni_id">Nama Unit</label>
                                        <select id="emp_uni_id" name="emp_uni_id" placeholder="Isi nama unit" class="form-control">
                                          <<option value="">-- Pilih Unit --</option>
                                          <?php foreach($optUnit['unit'] as $key1 => $value1): ?>
                                            <optgroup label="<?php echo $optUnit['bagian'][$key1]; ?>">
                                            <?php foreach($value1 as $value2): ?>
                                            <option value="<?php echo $value2['key']; ?>"><?php echo $value2['value']; ?></option>
                                            <?php endforeach; ?>
                                            </optgroup>
                                          <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="emp_jab_id">Nama Jabatan</label>
                                        <select id="emp_jab_id" name="emp_jab_id" placeholder="Isi nama jabatan" class="form-control">
                                          <<option value="">-- Pilih Jabatan --</option>
                                          <?php foreach($optJabatan as $value): ?>
                                          <option value="<?php echo $value['key']; ?>"><?php echo $value['value']; ?></option>
                                          <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                    <div style="display: inline-block;float: left;">
                      <label><input name="autoClose" id="autoClose" type="checkbox" class="i-checks"> Auto-Close Enable </label>
                    </div>
                    <a class="btn btn-default prev" href="#">Previous</a>
                    <a class="btn btn-default next" href="#">Next</a>
                    <button class="ladda-button ladda-button-demo btn btn-success" data-style="expand-right">Save</button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>



<!-- Vendor scripts -->
<script src="<?php echo $baseUrl; ?>assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/slimScroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/metisMenu/dist/metisMenu.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/iCheck/icheck.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/sparkline/index.js"></script>
<!-- DataTables -->
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- DataTables buttons scripts -->
<script src="<?php echo $baseUrl; ?>assets/vendor/pdfmake/build/pdfmake.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/pdfmake/build/vfs_fonts.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/jquery-validation/jquery.validate.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/ladda/dist/spin.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/ladda/dist/ladda.min.js"></script>
<script src="<?php echo $baseUrl; ?>assets/vendor/ladda/dist/ladda.jquery.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/toastr/build/toastr.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/sweetalert/lib/sweet-alert.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/iCheck/icheck.min.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/moment/moment.js"></script>

<script src="<?php echo $baseUrl; ?>assets/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js"></script>

<script src="https://cdn.jsdelivr.net/autonumeric/2.0.0/autoNumeric.min.js"></script>

<!-- App scripts -->
<script src="<?php echo $baseUrl; ?>assets/scripts/homer.js"></script>

<script type="text/javascript">
  function session_checking()
  {
    $.post( '<?php echo $baseUrl ?>api/session/check', function( data ) {
        if(data.loggedIn == 0)
        {
            swal({
                title: "Session Expired!!",
                text: "Your will be redirect to the login page",
                type: "warning",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "OK"
            },
            function () {
                location.reload();
            });
        }
    }, 'json');
  }
  var validateSession = setInterval(session_checking, 5000);
</script>


<script>

    $(function () {

      var l = $( '.ladda-button-demo' ).ladda();
      var frm = $('#form_2');

      // Toastr options
      toastr.options = {
          "debug": false,
          "newestOnTop": false,
          "positionClass": "toast-top-center",
          "closeButton": true,
          "toastClass": "animated fadeInDown",
      };

        // Initialize Example 1
        var table = $('#example1').DataTable( {
            "ajax": '<?php echo $baseUrl; ?>api/employee/lists',
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
            "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
            buttons: [
                {extend: 'copy',className: 'btn-sm'},
                {extend: 'csv',title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'pdf', title: 'ExampleFile', className: 'btn-sm'},
                {extend: 'print',className: 'btn-sm'}
            ],
            "columnDefs": [
              {
                "targets": -1,
                "data": null,
                "defaultContent": '<button class="btn btn-info btn-xs btnEdit" type="button"><i class="fa fa-paste"></i> Edit</button> <button class="btn btn-danger btn-xs btnDelete" type="button"><i class="fa fa-trash-o"></i> <span class="bold">Delete</span></button>'
              },
              {
                "targets": [ 1 ],
                "visible": false,
                "searchable": false
              },
            ]
        });

        var fillInputForm = function(data) {
          $.each(data, function(idx, val){
            $('#'+idx).val(val);
          });
        };

        $('#example1 tbody').on( 'click', '.btnEdit', function () {
            var data = table.row( $(this).parents('tr') ).data();
            frm.attr('action', '<?php echo $baseUrl ?>api/employee/edit?<?php echo $primaryKey; ?>=' + data[ 1 ]);
            $.get( frm.attr('action'), function(data) {
              fillInputForm(data);
              $('#btnAdd').trigger('click');
            }, 'json').fail(function() {
              toastr.error('Request data failed!');
            });
        } );

        $('#example1 tbody').on( 'click', '.btnDelete', function () {
            var data = table.row( $(this).parents('tr') ).data();
            swal({
              title: "Are you sure?",
              text: "Data will be delete!",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Yes, delete it!",
              cancelButtonText: "No, cancel!",
              closeOnConfirm: false,
              closeOnCancel: false },
              function (isConfirm) {
                if (isConfirm) {
                  $.post('<?php echo $baseUrl; ?>api/employee/delete',{<?php echo $primaryKey; ?>:data[ 1 ]},function(data) {
      							if(data.success == true) {
      								swal("Deleted!", data.message, "success");
                      table.ajax.reload( null, false ); // user paging is not reset on reload
      							} else {
      								swal("Cancelled!", "Oops.. " + data.message, "error");
      							}
                    setTimeout(function(){$('.sweet-alert .confirm').trigger('click');}, 1500);
      						},'json');
                } else {
                    swal("Cancelled", "Your data is safe :)", "error");
                    setTimeout(function(){$('.sweet-alert .confirm').trigger('click');}, 1500);
                }
              }
            );
        } );

        var validator = frm.validate({
            rules: {
                emp_name: {
                    required: true
                }
            },
            submitHandler: function(form) {
              // Start loading
              l.ladda( 'start' );

              $.ajax({
                url: frm.attr('action'),
                method: "POST",
                data: frm.serializeArray(),
                dataType: "json"
              }).done(function( data ) {
                if(data.success == true) {
                  toastr.success(data.message);
                  table.ajax.reload( null, false ); // user paging is not reset on reload
                  if($('#<?php echo $primaryKey; ?>').val() == '') {
                    frm.find(':input').val('');
                    $("#<?php echo $inputFocus; ?>").focus();
                  }
                  if($('#autoClose').is(":checked")) $("#myModal5").modal('hide');
                  validator.resetForm();
                  $('.form-control.error').removeClass('error');
                } else {
                  toastr.error('Oops.. ' + data.message);
                }
                l.ladda('stop');
              }).fail(function( jqXHR, textStatus ) {
                toastr.error('Request data failed!');
                l.ladda('stop');
              })
            },
            errorPlacement: function(error, element) {
                $( element )
                        .closest( "form" )
                        .find( "label[for='" + element.attr( "id" ) + "']" )
                        .append( error );
            },
            errorElement: "span",
        });

        $("#myModal5").on("hidden.bs.modal", function () {
            frm.find(':input').val('');
            frm.attr('action', '<?php echo $baseUrl ?>api/employee/add');
            validator.resetForm();
            $('.form-control.error').removeClass('error');
            $('#ln-tb-step1').trigger('click');
        });

        $('.ln-tb-step').click(function(){
          $('.ln-tb-step').removeClass('tb-active');
          $(this).addClass('tb-active');
        });

        $('.prev').click(function(){
          var id = ($('.tb-active').attr('href')).replace( /^\D+/g, '');
          id = parseInt(id);
          if(id > 1) $('#ln-tb-step'+(id-1)).trigger('click');
        });

        $('.next').click(function(){
          var id = ($('.tb-active').attr('href')).replace( /^\D+/g, '');
          id = parseInt(id);
          if(id < 4) $('#ln-tb-step'+(id+1)).trigger('click');
        });

        $('.datepicker').datepicker({autclose: true}).on('changeDate', function (ev) {
          $(this).datepicker('hide');
        });

        // The options are...optional :)
        const autoNumericOptionsEuro = {
            digitGroupSeparator        : '.',
            decimalCharacter           : ',',
            minimumValue      : '0',
            maximumValue : '1000000000'
        };

        $('.autonumeric').autoNumeric('init', autoNumericOptionsEuro);

    });

</script>

</body>
</html>
