<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>REPORT ABSENCE | WebApp admin theme</title>
</head>
<body>
<table width="100%">
  <tr>
    <td>
      <table width="40%">
        <tr>
          <td colspan="3">
            Laporan Absen Karyawan
          </td>
        </tr>
        <tr>
          <td width="30%">NIK</td>
          <td>:</td>
          <td><?php echo $employee->emp_code; ?></td>
        </tr>
        <tr>
          <td>Nama Pegawai</td>
          <td>:</td>
          <td><?php echo $employee->emp_name; ?></td>
        </tr>
        <tr>
          <td>Departemen</td>
          <td>:</td>
          <td><?php echo $employee->uni_name; ?></td>
        </tr>
        <tr>
          <td>Bulan</td>
          <td>:</td>
          <td><?php echo $arrMonthName[(int)$month]; ?></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table border="1" cellpadding="5" cellspacing="0">
        <tr>
          <th rowspan="2">No</th>
          <th rowspan="2">Hari</th>
          <th rowspan="2">Tanggal</th>
          <th rowspan="2">Shif</th>
          <th colspan="2">Jam</th>
          <th colspan="3">Terlambat</th>
          <th colspan="<?php echo $cntIzinTidakHadir; ?>">Tidak Masuk</th>
          <th colspan="2">Apel</th>
          <th rowspan="2">Keterangan</th>
        </tr>
        <tr>
          <th>Masuk</th>
          <th>Pulang</th>
          <th>Menit</th>
          <th>Jumlah</th>
          <th>Dengan Izin</th>
          <?php foreach($izinTidakHadir as $value): ?>
          <th><?php echo $value->sta_name; ?></th>
          <?php endforeach; ?>
          <th>Hadir Apel</th>
          <th>Apel</th>
        </tr>
        <?php $cnt = 0; $arrJumlah = [
          'jumlahMasuk' => 0,
          'jumlahMenitTerlambat' => 0,
          'jumlahTerlambat' => 0,
          'denganIzinTerlambat' => 0,
          'tidakMasuk' => [],
          'hadirApel' => 0,
          'apel' => 0,
        ]; ?>
        <?php for($i=1; $i<=$totalDay; $i++): ?>
        <?php $dayNo = date('w', mktime(0, 0, 0, $month, $i, $year)); $tgl = ($i < 10 ? "0$i" : $i) . "/$month/$year"; ?>
        <?php //if($dayNo == 0) continue; $cnt++; ?>
        <?php
        $statusLate = false;
        $totalMinuteLate = 0;
        $hadirApel = 0;
        $apel = 0;

        $tanggal = $i < 10 ? ('0'.$i) : $i;
        $generateId = $year . $month . $tanggal . $empId;
        $scheduleDate = $year . '-' . $month . '-' . $tanggal;

        $absenceLabel = !empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min']) ? ($dataEmpAbsence[$empCode][$scheduleDate]['time_min'].' - '.$dataEmpAbsence[$empCode][$scheduleDate]['time_max']) : 'OFF';

        if(!empty($dataEmpAbsence[$empCode][$scheduleDate]) AND !empty($dataEmpHasSchedule['detail'][$empId][$generateId])) {
          $intMinSchedule = strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_min']));
          $intMaxSchedule = strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_max']));
          $intMinAbsence = strtotime($dataEmpAbsence[$empCode][$scheduleDate]['wkt_min']);
          $intMaxAbsence = strtotime($dataEmpAbsence[$empCode][$scheduleDate]['wkt_max']);

          $apelSchedule = strtotime($scheduleDate . ' ' . $setting['apel_closest_schedule']);
          $apelTime = strtotime($scheduleDate . ' ' . $setting['apel_time']);
          $apelDay = $setting['apel_day'];

          //echo "string - x -" . $apelSchedule;
          //echo "string - y -" . $intMinSchedule;
          if($apelSchedule == $intMinSchedule AND strtolower($arrDayName[$dayNo]) == $apelDay) {
            $apel = 1;
            $arrJumlah['apel'] += 1;
            if($intMinAbsence <= $apelTime) {
              $hadirApel = 1;
              $arrJumlah['hadirApel'] += 1;
            }
          }

          if(($intMinAbsence >= $intMinSchedule AND $intMinAbsence <= $intMaxSchedule) OR ($intMaxAbsence >= $intMinSchedule AND $intMaxAbsence <= $intMaxSchedule) OR ($intMinAbsence <= $intMinSchedule AND $intMaxAbsence >= $intMaxSchedule)) {
            $late = strtotime('+'.$setting['toleransi_in'].' minutes', strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_min'])));
            if($intMinAbsence > $late) {
              $statusLate = true;
              $totalMinuteLate = (int)date('i', ($intMinAbsence - $late));
              $arrJumlah['jumlahMenitTerlambat'] += $totalMinuteLate;
              $arrJumlah['jumlahTerlambat'] += 1;
            }
          }
        }

        if(!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min'])) $arrJumlah['jumlahMasuk'] += 1;

        ?>
        <tr>
          <td><?php echo $i; ?></td>
          <td><?php echo $arrDayName[$dayNo]; ?></td>
          <td><?php echo $tgl; ?></td>
          <td><?php echo (!empty($dataEmpHasSchedule['detail'][$empId][$generateId]['code']) ? $dataEmpHasSchedule['detail'][$empId][$generateId]['code'] : ''); ?></td>
          <td><?php echo (!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min']) ? $dataEmpAbsence[$empCode][$scheduleDate]['time_min'] : ''); ?></td>
          <td><?php echo (!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_max']) ? $dataEmpAbsence[$empCode][$scheduleDate]['time_max'] : ''); ?></td>
          <td><?php if($statusLate) echo $totalMinuteLate; ?></td>
          <td><?php if($statusLate) echo 1; ?></td>
          <td><?php if($statusLate AND !empty($dataEmpHasSchedule['izin'][$empId][$generateId])) {$arrJumlah['denganIzinTerlambat'] += 1; echo 1;} ?></td>

          <?php foreach($izinTidakHadir as $value): ?>
          <td><?php if(!empty($dataEmpHasSchedule['izin'][$empId][$generateId][$value->sta_id])) {
            $arrJumlah['tidakMasuk'][$value->sta_id] = (!empty($arrJumlah['tidakMasuk'][$value->sta_id]) ? ($arrJumlah['tidakMasuk'][$value->sta_id] + 1) : 1); echo 1;
          } elseif(!empty($dataEmpHasCuti[$empId][$generateId][$value->sta_id])) {
            $arrJumlah['tidakMasuk'][$value->sta_id] = (!empty($arrJumlah['tidakMasuk'][$value->sta_id]) ? ($arrJumlah['tidakMasuk'][$value->sta_id] + 1) : 1); echo 1;
          } ?></td>
          <?php endforeach; ?>

          <td><?php echo (!empty($hadirApel) ? $hadirApel : ''); ?></td>
          <td><?php echo (!empty($apel) ? $apel : ''); ?></td>
          <td></td>
        </tr>
        <?php endfor; ?>
        <tr>
          <td colspan="4">Jumlah</td>
          <td><?php echo $arrJumlah['jumlahMasuk']; ?></td>
          <td><?php echo $arrJumlah['jumlahMasuk']; ?></td>
          <td><?php echo $arrJumlah['jumlahMenitTerlambat']; ?></td>
          <td><?php echo $arrJumlah['jumlahTerlambat']; ?></td>
          <td><?php echo $arrJumlah['denganIzinTerlambat']; ?></td>
          <?php foreach($izinTidakHadir as $value): ?>
          <td><?php echo (!empty($arrJumlah['tidakMasuk'][$value->sta_id]) ? $arrJumlah['tidakMasuk'][$value->sta_id] : 0); ?></td>
          <?php endforeach; ?>
          <td><?php echo $arrJumlah['hadirApel']; ?></td>
          <td><?php echo $arrJumlah['apel']; ?></td>
          <td></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr><td>&nbsp;</td></tr>
  <!--<tr>
    <td>
      <table border="1" cellpadding="5" cellspacing="0" width="40%">
        <tr>
          <th>Shift</th>
          <th>Hari Biasa</th>
          <th>Minggu / Libur</th>
          <th>Waktu Kerja</th>
        </tr>
        <tr>
          <td>1</td>
          <td>14</td>
          <td>0</td>
          <td>112</td>
        </tr>
        <tr>
          <td>2</td>
          <td>12</td>
          <td>0</td>
          <td>96</td>
        </tr>
        <tr>
          <td>3</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
        </tr>
        <tr>
          <td colspan="3">Total Waktu</td>
          <td>208</td>
        </tr>
      </table>
    </td>
  </tr>-->
</table>
</body>
</html>
