<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>REPORT ABSENCE | WebApp admin theme</title>
    <style type="text/css">
        table {
            page-break-inside: auto
        }

        tr {
            page-break-inside: avoid;
            page-break-after: auto
        }

        @media print {
            table {
                font-size: 10px;
                border-spacing: 0;
                border-collapse: collapse;
            }

            td, th {
                padding: 3px;
            }

            .page-break {
                display: block;
                page-break-before: always;
            }
        }
    </style>
</head>
<body>
<?php if (!empty($data)): ?>
    <table width="100%">
        <tr>
            <td>
                <table width="40%">
                    <tr>
                        <td colspan="3">
                            Laporan Schedule Karyawan
                        </td>
                    </tr>
                    <tr>
                        <td>Departemen</td>
                        <td>:</td>
                        <td><?php echo $bagian->bag_name; ?></td>
                    </tr>
                    <tr>
                        <td>Bulan</td>
                        <td>:</td>
                        <td><?php echo $arrMonthName[(int)$month] . ' ' . $year;?></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <table border="1" cellpadding="5" cellspacing="0">
                    <tr>
                        <th>No</th>
                        <th>ID</th>
                        <th>NPK</th>
                        <th>Nama</th>
                        <?php 
                            $endDate = date('t', strtotime($year.'-'.$month.'-01'));
                            for ($i=1; $i <= $endDate; $i++):
                                $d = ($i < 10 ? ('0'.$i) : $i);
                                $tgl = $year.'-'.$month.'-'.$d;
                        ?>
                            <th><?php echo $d; ?></th>
                        <?php endfor; ?>
                    </tr>
                    <?php foreach($data as $val): ?>
                        <tr>
                        <?php foreach($val as $val2): ?>
                            <td><?php echo $val2; ?></td>
                        <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </td>
        </tr>
    </table>
    <div class="page-break"></div>

    <?php if (empty($isExcel)): ?>
        <div style="margin-top: 20px;">
            <a href="<?php echo $actualLink; ?>&excel=1">EXPORT TO EXCEL</a>
        </div>
    <?php endif; ?>
<?php else: ?>
    <p>Oops.. data kosong</p>
<?php endif; ?>
</body>
</html>
