<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>REPORT ABSENCE | WebApp admin theme</title>
    <style type="text/css">
        table { page-break-inside:auto }
        tr    { page-break-inside:avoid; page-break-after:auto }
        @media print{
            table {font-size: 10px;border-spacing:0;border-collapse:collapse;}
            td, th {padding:3px;}
            .page-break	{ display: block; page-break-before: always; }
        }
    </style>
</head>
<body>
  <?php $arrDataTotal = []; ?>
<?php if(!empty($data)): ?>
<?php foreach($data as $key => $value): ?>
  <?php if(empty($value)) continue; $first = true; ?>
<?php foreach($value as $key2 => $value2): ?>
<?php extract($value2); ?>
<table width="100%">
  <?php if($first): ?>
  <tr>
    <td>
      <table width="40%">
        <tr>
          <td colspan="3">
            Laporan Absen Karyawan
          </td>
        </tr>
        <tr>
          <td width="30%">NIK</td>
          <td>:</td>
          <td><?php echo $employee->emp_code; ?></td>
        </tr>
        <tr>
          <td>Nama Pegawai</td>
          <td>:</td>
          <td><?php echo $employee->emp_name; ?></td>
        </tr>
        <tr>
          <td>Departemen</td>
          <td>:</td>
          <td><?php echo $employee->uni_name; ?></td>
        </tr>
        <tr>
          <td>Tahun</td>
          <td>:</td>
          <td><?php echo $year; ?></td>
        </tr>
      </table>
    </td>
  </tr>
  <?php $first = false; endif; ?>
  <!-- <tr>
    <td>
      <table border="1" cellpadding="5" cellspacing="0"> -->
        <!-- <tr>
          <th>Keterangan</th>
          <th>Total Masuk</th>
          <th>Total Pulang</th>
          <th>Total Datang Lambat</th>
          <th>Total Pulang Cepat</th>
          <?php foreach($izinTidakHadir as $value): ?>
          <th><?php echo $value->sta_name; ?></th>
          <?php endforeach; ?>
          <th>Hadir Apel</th>
          <th>Apel</th>
        </tr> -->
        <?php $cnt = 0; $arrJumlah = [
          'jumlahMasuk' => 0,
          'jumlahMenitTerlambat' => 0,
          'jumlahTerlambat' => 0,
          'jumlahMenitPulangCepat' => 0,
          'jumlahPulangCepat' => 0,
          'denganIzinTerlambat' => 0,
          'tidakMasuk' => [],
          'hadirApel' => 0,
          'apel' => 0,
          'jumlahShiftBiasa' => [],
          'jumlahShiftLibur' => [],
          'waktuKerja' => [],
        ];

        $arrShift = [];
        ?>
        <?php $tanggalStart = $setting['tanggal_cutoff']; $nowMonth = $month;  ?>
        <?php for($i=0; $i<=$totalDay; $i++): ?>
        <?php

          $month = $nowMonth;
          $day = $tanggalStart + $i;
          if($day > $endDay) {
            $day = $day - $endDay;

            $month = (int)$nowMonth + 1;

            if($month > 12) $year += 1;

            $month = $month < 9 ? "0$month" : $month;
          }

          $dayNo = date('w', mktime(0, 0, 0, $month, $day, $year));
          $tgl = ($day < 10 ? "$day" : $day) . "/$month/$year";
        ?>
        <?php //if($dayNo == 0) continue; $cnt++; ?>
        <?php
        $statusLate = false;
        $totalMinuteLate = 0;
        $statusEearlyOut = false;
        $totalMinuteEearlyOut = 0;
        $hadirApel = 0;
        $apel = 0;

        $tanggal = $day < 10 ? ('0'.$day) : $day;
        $generateId = $year . $month . $tanggal . $empId;
        $scheduleDate = $year . '-' . $month . '-' . $tanggal;

        $absenceLabel = !empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min']) ? ($dataEmpAbsence[$empCode][$scheduleDate]['time_min'].' - '.$dataEmpAbsence[$empCode][$scheduleDate]['time_max']) : 'OFF';

        if(!in_array($dayNo, [6,0])) {
          if(empty($dataEmpHasSchedule['detail'][$empId][$generateId])) {
            if($dayNo == 5) { //hari jumat
              $wktMin = $setting['default_2_schedule_in'];
              $wktMax = $setting['default_2_schedule_out'];
            } else {
              $wktMin = $setting['default_1_schedule_in'];
              $wktMax = $setting['default_1_schedule_out'];
            }

            $dataEmpHasSchedule['detail'][$empId][$generateId] = [
              'wkt_min' => $wktMin,
              'wkt_max' => $wktMax,
              'code' => 'NORM',
              'color' => '#000000',
              'namaIzin' => '',
              'status_reason' => '',
              'isScheduleGantiHari' => 0,
            ];
          }
        }

        $totalMinuteLate = 0;
        $totalMinuteEearlyOut = 0;

        if(!empty($dataEmpAbsence[$empCode][$scheduleDate]) AND !empty($dataEmpHasSchedule['detail'][$empId][$generateId])) {
          $intMinSchedule = strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_min']));
          $intMaxSchedule = strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_max']));
          $intMinAbsence = strtotime($dataEmpAbsence[$empCode][$scheduleDate]['wkt_min']);
          $intMaxAbsence = strtotime($dataEmpAbsence[$empCode][$scheduleDate]['wkt_max']);

          $apelSchedule = strtotime($scheduleDate . ' ' . $setting['apel_closest_schedule']);
          $apelTime = strtotime($scheduleDate . ' ' . $setting['apel_time']);
          $apelDay = $setting['apel_day'];

          //echo "string - x -" . $apelSchedule;
          //echo "string - y -" . $intMinSchedule;
          if($apelSchedule == $intMinSchedule AND strtolower($arrDayName[$dayNo]) == $apelDay) {
            $apel = 1;
            $arrJumlah['apel'] += 1;
            if($intMinAbsence <= $apelTime) {
              $hadirApel = 1;
              $arrJumlah['hadirApel'] += 1;
            }
          }

          if(($intMinAbsence >= $intMinSchedule AND $intMinAbsence <= $intMaxSchedule) OR ($intMaxAbsence >= $intMinSchedule AND $intMaxAbsence <= $intMaxSchedule) OR ($intMinAbsence <= $intMinSchedule AND $intMaxAbsence >= $intMaxSchedule)) {
            $earlyOut = strtotime('-'.$setting['toleransi_out'].' minutes', strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_max'])));
            $late = strtotime('+'.$setting['toleransi_in'].' minutes', strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_min'])));
            if($intMinAbsence > $late) {
              $statusLate = true;
              $totalMinuteLate = date('h:i', ($intMinAbsence - $intMinSchedule));
              list($hour, $minute) = explode(':', $totalMinuteLate);
              $hour = (int)$hour;
              $minute = (int)$minute;
              $hour = $hour > 0 ? (($hour-1)*60) : 0;
              $minute += $hour;
              $totalMinuteLate = $minute;
              $arrJumlah['jumlahMenitTerlambat'] += $minute;
              $arrJumlah['jumlahTerlambat'] += 1;
            }
            if($intMaxAbsence < $earlyOut) {
              $statusEearlyOut = true;
              $totalMinuteEearlyOut = date('h:i', ($intMaxSchedule - $intMaxAbsence));
              list($hour, $minute) = explode(':', $totalMinuteEearlyOut);
              $hour = (int)$hour;
              $minute = (int)$minute;
              $hour = $hour > 0 ? (($hour-1)*60) : 0;
              $minute += $hour;
              $totalMinuteEearlyOut = $minute;
              $arrJumlah['jumlahMenitPulangCepat'] += $minute;
              $arrJumlah['jumlahPulangCepat'] += 1;
            }
          }
        }

        if(!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min'])) $arrJumlah['jumlahMasuk'] += 1;

        if(!empty($dataEmpHasSchedule['detail'][$empId][$generateId]['code'])) {
          $arrShift[$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] = $dataEmpHasSchedule['detail'][$empId][$generateId]['code'];
          if(empty($arrJumlah['jumlahShiftBiasa'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']])) $arrJumlah['jumlahShiftBiasa'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] = 0;
          $arrJumlah['jumlahShiftBiasa'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] += 1;

          if(empty($arrJumlah['waktuKerja'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']])) $arrJumlah['waktuKerja'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] = 0;
          $arrJumlah['waktuKerja'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] += !empty($dataEmpAbsence[$empCode][$scheduleDate]['totalWaktu']) ? $dataEmpAbsence[$empCode][$scheduleDate]['totalWaktu'] : 0;

          if($dayNo == 0) {
            if(empty($arrJumlah['jumlahShiftLibur'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']])) $arrJumlah['jumlahShiftLibur'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] = 0;
            $arrJumlah['jumlahShiftLibur'][$dataEmpHasSchedule['detail'][$empId][$generateId]['code']] += 1;
          }

          if(!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min']) AND !empty($dataEmpAbsence[$empCode][$scheduleDate]['time_max']) AND $dataEmpAbsence[$empCode][$scheduleDate]['time_min'] == $dataEmpAbsence[$empCode][$scheduleDate]['time_max']) {
            $settingBatasAbsenMasuk = $setting['batas_absen_masuk'] * 60;
            $batasAbsenMasuk = strtotime('+'.$settingBatasAbsenMasuk.' minutes', strtotime(($scheduleDate . ' ' . $dataEmpHasSchedule['detail'][$empId][$generateId]['wkt_min'])));

            if(!empty($totalMinuteLate)) $arrJumlah['jumlahMenitTerlambat'] -= $totalMinuteLate;
            if(!empty($totalMinuteLate)) $arrJumlah['jumlahTerlambat'] -= 1;
            if(!empty($totalMinuteEearlyOut)) $arrJumlah['jumlahMenitPulangCepat'] -= $totalMinuteEearlyOut;
            if(!empty($totalMinuteEearlyOut)) $arrJumlah['jumlahPulangCepat'] -= 1;

            if($intMinAbsence <= $batasAbsenMasuk) {
              $dataEmpAbsence[$empCode][$scheduleDate]['time_max'] = '';
              $totalMinuteEearlyOut = 225;
              $totalMinuteLate = '';
              $statusLate = '';
              $arrJumlah['jumlahMenitPulangCepat'] += $totalMinuteEearlyOut;
              $arrJumlah['jumlahPulangCepat'] += 1;
            } else {
              $dataEmpAbsence[$empCode][$scheduleDate]['time_min'] = '';
              $totalMinuteLate = 225;
              $totalMinuteEearlyOut = '';
              $statusEearlyOut = '';
              $arrJumlah['jumlahMenitTerlambat'] += $totalMinuteLate;
              $arrJumlah['jumlahTerlambat'] += 1;
            }
          }
        }

        if(in_array($dayNo, [6,0]) AND (!empty($dataEmpAbsence[$empCode][$scheduleDate]['time_min']) OR !empty($dataEmpAbsence[$empCode][$scheduleDate]['time_max']))) {
          $dataEmpAbsence[$empCode][$scheduleDate]['time_min'] = 'PIKET';
          $dataEmpAbsence[$empCode][$scheduleDate]['time_max'] = 'PIKET';
        }

        ?>
        <?php endfor; ?>
        <?php
          $arrDataTotal[$key2][0] = $arrJumlah['jumlahMasuk'];
          $arrDataTotal[$key2][1] = $arrJumlah['jumlahMasuk'];
          $arrDataTotal[$key2][2] = $arrJumlah['jumlahTerlambat'];
          $arrDataTotal[$key2][3] = $arrJumlah['jumlahPulangCepat'];
          $x = 4;
          foreach($izinTidakHadir as $value) {
            $arrDataTotal[$key2][$x] = (!empty($arrJumlah['tidakMasuk'][$value->sta_id]) ? $arrJumlah['tidakMasuk'][$value->sta_id] : 0);
            $x++;
          }
          $arrDataTotal[$key2][$x] = $arrJumlah['hadirApel'];
          $arrDataTotal[$key2][($x+1)] = $arrJumlah['apel'];
        ?>
        <!-- <tr>
          <td>Jumlah</td>
          <td><?php echo $arrJumlah['jumlahMasuk']; ?></td>
          <td><?php echo $arrJumlah['jumlahMasuk']; ?></td>
          <td><?php echo $arrJumlah['jumlahTerlambat']; ?></td>
          <td><?php echo $arrJumlah['jumlahPulangCepat']; ?></td>
          <?php foreach($izinTidakHadir as $value): ?>
          <td><?php echo (!empty($arrJumlah['tidakMasuk'][$value->sta_id]) ? $arrJumlah['tidakMasuk'][$value->sta_id] : 0); ?></td>
          <?php endforeach; ?>
          <td><?php echo $arrJumlah['hadirApel']; ?></td>
          <td><?php echo $arrJumlah['apel']; ?></td>
        </tr> -->
      <!-- </table>
    </td>
  </tr> -->

  </table>
  <?php endforeach; ?>
  <table width="100%">
    <tr>
      <td>
        <table border="1" cellpadding="5" cellspacing="0" width="100%">
          <tr>
            <th width="15%">Keterangan</th>
            <?php for($i=1;$i<=12;$i++): ?>
            <th width="80px"><?php echo $arrMonthName[$i]; ?></th>
            <?php endfor; ?>
          </tr>
          <tr>
            <td>Total Masuk</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][0]) ? $arrDataTotal[$i][0] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
          <tr>
            <td>Total Pulang</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][1]) ? $arrDataTotal[$i][1] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
          <tr>
            <td>Total Datang Lambat</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][2]) ? $arrDataTotal[$i][2] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
          <tr>
            <td>Total Pulang Cepat</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][3]) ? $arrDataTotal[$i][3] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
          <?php foreach($izinTidakHadir as $value): $x = 4; ?>
          <tr>
            <td><?php echo $value->sta_name; ?></td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][$x]) ? $arrDataTotal[$i][$x] : 0 ); ?></td>
            <?php $x++; endfor; ?>
          </tr>
          <?php endforeach; ?>
          <tr>
            <td>Total Hadir Apel</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][$x]) ? $arrDataTotal[$i][$x] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
          <tr>
            <td>Total Apel</td>
            <?php for($i=1;$i<=12;$i++): ?>
            <td><?php echo (!empty($arrDataTotal[$i][($x+1)]) ? $arrDataTotal[$i][($x+1)] : 0 ); ?></td>
            <?php endfor; ?>
          </tr>
        </table>
      </td>
    </tr>
  </table>
  <div class="page-break"></div>
<?php endforeach; ?>
    <?php if(empty($isExcel)): ?>
        <div style="margin-top: 20px;">
            <a href="<?php echo $actualLink; ?>&excel=1">EXPORT TO EXCEL</a>
        </div>
    <?php endif; ?>
<?php else: ?>
<p>Oops.. data kosong</p>
<?php endif; ?>
</body>
</html>
