<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>HOMER | WebApp admin theme</title>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!--<link rel="shortcut icon" type="image/ico" href="favicon.ico" />-->

    <!-- Vendor styles -->
    <link rel="stylesheet" href="../public/assets/vendor/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="../public/assets/vendor/metisMenu/dist/metisMenu.css" />
    <link rel="stylesheet" href="../public/assets/vendor/animate.css/animate.css" />
    <link rel="stylesheet" href="../public/assets/vendor/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" href="../public/assets/vendor/sweetalert/lib/sweet-alert.css" />

    <!-- App styles -->
    <link rel="stylesheet" href="../public/assets/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="../public/assets/fonts/pe-icon-7-stroke/css/helper.css" />
    <link rel="stylesheet" href="../public/assets/styles/style.css">

</head>
<body class="blank">

<!-- Simple splash screen-->
<div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
<!--[if lt IE 7]>
<p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div class="color-line"></div>

<div class="login-container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center m-b-md">
                <h3><?php echo __('Aplikasi Absensi RS'); ?></h3>
                <small><?php echo __('Silahkan login menggunakan username dan password yang sudah terdaftar'); ?></small>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                        <form action="<?php echo $baseUrl; ?>api/login" method="post" id="frm">
                            <div class="form-group">
                                <label class="control-label" for="username">Username</label>
                                <input type="text" placeholder="username" title="Please enter you username" required="" value="" name="usr_username" id="usr_username" class="form-control">
                                <span class="help-block small">Your unique username to app</span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="password">Password</label>
                                <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="usr_password" id="usr_password" class="form-control">
                                <span class="help-block small">Yur strong password</span>
                            </div>
                            <div class="checkbox">
                                <input type="checkbox" class="i-checks" checked>
                                     Remember login
                                <p class="help-block small">(if this is a private computer)</p>
                            </div>
                            <button id="btnLogin" type="submit" class="btn btn-success btn-block">Login</button>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Vendor scripts -->
<script src="../public/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="../public/assets/vendor/jquery-ui/jquery-ui.min.js"></script>
<script src="../public/assets/vendor/slimScroll/jquery.slimscroll.min.js"></script>
<script src="../public/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../public/assets/vendor/metisMenu/dist/metisMenu.min.js"></script>
<script src="../public/assets/vendor/iCheck/icheck.min.js"></script>
<script src="../public/assets/vendor/sparkline/index.js"></script>
<script src="../public/assets/vendor/sweetalert/lib/sweet-alert.min.js"></script>

<!-- App scripts -->
<script src="../public/assets/scripts/homer.js"></script>

<script type="text/javascript">
  $(function(){
      var frm = $('#frm');
      $('#btnLogin').click(function(e){
        e.preventDefault();
        $.ajax({
      		url: frm.attr('action'),
      		method: "POST",
      		data: frm.serializeArray(),
      		dataType: "json"
      	}).done(function( data ) {
          if(data.count > 0) {
            swal({
                title: "Good job!",
                text: "Login success!",
                type: "success"
            });
            setTimeout(function(){ window.location.href = "<?php echo $baseUrl; ?>"; }, 2000);
          } else {
            swal({
                title: "Oops..",
                text: "Username or password is wrong!",
                type: "error"
            });
          }
      	}).fail(function( jqXHR, textStatus ) {
      		alert( "Request failed: " + textStatus );
      	})
      });
  });
</script>

</body>
</html>
